### ISSUE TITLE
Magical numbers

### ISSUE THREAD

**Issue by yveshanoulle** [schnidrig/openhab2-rollershutters#2]
Hi 
Your script contains magical numbers like 240, 160, etc.

I don't understand what they mean of what they intend to do. I assume making them variables (constants) would made the script clearer and more easy to adapt .

**Comment by schnidrig** [comment]
Those numbers are all part of the test code. They are not magical but simply test data. You can recognise tests by their name. They are all called "<something>Test."

So no, I will not make them constants. That makes no sense to me.

**Comment by yveshanoulle** [comment]
I was talking about the numbers below. 
In that script the word test is not used.
For you it might be clear what these numbers mean, for me not.



########################
items:
  azimuth: astro_sun_azimuth
  elevation: astro_sun_elevation
  weather_sunny: weather_sunny
  shutter_automation: shutter_automation

########################
# SUN exposure
 
sun_exposure:
  shutter_living:
    orientation: 240
    sun_openings:
      - azimuth: 160
        below:
          - { azimuth: 240, elevation: 60}
        above:
          - { elevation: 5}
      - azimuth: 240
        below:
          - { azimuth: 240, elevation: 60}
          - { azimuth: 280, elevation: 10}
        above:
          - { azimuth: 240, elevation: 3}
      - azimuth: 330
  shutter_kitchen:
    orientation: 150
    sun_openings:
      - azimuth: 80
      - azimuth: 220
  shutter_office:
    orientation: 60
    sun_openings:
      - azimuth: 30
      - azimuth: 140
  shutter_kids:
    orientation: 240
    sun_openings:
      - azimuth: 160
      - azimuth: 330
  shutter_bedroom:
    orientation: 240
    sun_openings:
      - azimuth: 160
      - azimuth: 330

**Comment by schnidrig** [comment]
That is not a script, but a config example. This will be entirely different for anyone else. In fact I don't know a house where this would be correct. It is merely an example.

azimuth and elevation are defined by the astro binding. maybe you want to take a minute or two to try to understand the astro binding and all of its values.

Again. I don't see how giving names to those numbers would make a difference. They have no meaning other than describing the windows of a virtual example house.

maybe you want to google a few terms like "profile angle sun" or "sun azimuth" "sun elevation"

**Comment by yveshanoulle** [comment]
What I'm telling you is that your example is not clear for someone who did not created it.
 The fact your are telling people to use google to understand your own example gives the message that you are missing information in the file.
 When I google "profile angle sun" I receive 9.940.000 results. I'm pretty sure that the first links I wil see are different then the once you will see. Which makes the chance that I interpret these numbers different then you is pretty high and will give your users a problem at a later phase.

I'm also confused by the fact you use an example file that you know can't be correct.
That tells me you did not test your example file. which is also a quality risk. 
This means I as a use will use a file that is never tested, I will run into a problem, where I don't know if I'm screwing up (which will be my default thinking) , yet it can be a stupid typing mistake creating the example file.

**Comment by schnidrig** [comment]
I'm sorry, but I do not understand your issue here. 

I can't write a schedule config for you since I don't know when you get up in the morning. 
Similarly I can't write a shutter config for you since I don't know where you live. The sample config does not work for my house, since I don't want to publish personal data about my house. Other than that the config is ok. It is an example. Nothing more nothing less.

What the values mean is described in the readme. Maybe that is not good enough for you to grasp the concept behind it. Therefore, I suggested you read up a bit about the subject. Anything you read about it will probably help. It's not that complicated after all. You just need to see a graph explaining what elevation, azimuth etc mean.
